# Generated by Django 4.0.3 on 2022-04-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_perfil_imagem_alter_vendedor_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='cnpj',
            field=models.CharField(help_text='CNPJ sem formatação', max_length=14, verbose_name='CNPJ sem formatação'),
        ),
    ]
