# Generated by Django 4.0.3 on 2022-04-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_carrinho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrinho',
        ),
    ]
