# Generated by Django 4.0.3 on 2022-03-31 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=96, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.TextField(verbose_name='Nome da loja')),
                ('nome_completo', models.TextField(verbose_name='Nome completo')),
                ('cnpj', models.TextField(max_length=14, verbose_name='CNPJ')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('telefone', models.TextField(max_length=11, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=96, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('descricao_html', models.TextField(verbose_name='Descrição em HTML')),
                ('preco', models.IntegerField(verbose_name='Preço')),
                ('imagem', models.ImageField(null=True, upload_to='mercado/covers/%Y/%m/%d/')),
                ('desconto', models.FloatField(verbose_name='Porcentagem do desconto')),
                ('com_desconto', models.BooleanField(verbose_name='O Produto está com desconto')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mercado.categoria')),
                ('vendendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.vendedor')),
            ],
        ),
    ]
