# Generated by Django 4.0.3 on 2022-05-01 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=96, verbose_name='Categoria')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Slug da categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Motorola Moto g10', max_length=96, verbose_name='Nome')),
                ('descricao', models.TextField(help_text='Ex: Este é o melhor produto do mundo', verbose_name='Descrição')),
                ('descricao_html', models.TextField(blank=True, help_text='Ex: <h1>Este é o melhor produto do mundo</h1>', verbose_name='Descrição em HTML')),
                ('is_descricao_html', models.BooleanField()),
                ('is_ativo', models.BooleanField(default=False)),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('imagem', models.ImageField(upload_to='mercado/covers/%Y/%m/%d/')),
                ('desconto', models.FloatField(blank=True, null=True, verbose_name='Porcentagem do desconto')),
                ('com_desconto', models.BooleanField(blank=True, verbose_name='O Produto está com desconto')),
                ('data_criacao', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mercado.categoria')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
