# Generated by Django 4.0.3 on 2022-04-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug da categoria'),
        ),
    ]
