# Generated by Django 4.0.3 on 2022-08-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_alter_produto_descricao_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='is_descricao_html',
            field=models.BooleanField(default=False),
        ),
    ]
