# Generated by Django 4.0.3 on 2022-04-11 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_vendedor_cnpj'),
        ('mercado', '0003_categoria_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_criacao',
            field=models.DateField(auto_now=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='com_desconto',
            field=models.BooleanField(blank=True, verbose_name='O Produto está com desconto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(help_text='Ex: Este é o melhor produto do mundo', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_html',
            field=models.TextField(blank=True, help_text='Ex: <h1>Este é o melhor produto do mundo</h1>', verbose_name='Descrição em HTML'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(help_text='Ex: Motorola Moto g10', max_length=96, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='vendendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vendedor'),
        ),
    ]
