# Generated by Django 4.0.3 on 2022-04-11 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0004_produto_data_criacao_alter_produto_com_desconto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='vendendor',
            new_name='vendedor',
        ),
    ]
