# Generated by Django 4.0.3 on 2022-04-11 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_vendedor_cnpj'),
        ('mercado', '0005_rename_vendendor_produto_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vendedor'),
        ),
    ]
