# Generated by Django 4.0.3 on 2022-04-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0008_carrinho_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
    ]
